### PR TITLE
Update definition file to CANNON.js 0.6.2

### PR DESCRIPTION
**Pull request by elisee**
Hi!

Here's an updated `cannon.d.ts`. I did some reviewing and fixing but most of the work was done by @harraps (who agreed to let me submit it here for him).

### CODE REVIEW

**Comment by clark-stevenson** [comment]
@elisee  awesome as always, I had forgotten about this, we did a rough d.ts for a project, but at the time Cannon did not have the kind of constraint we needed.  It is awesome to see @harraps and yourself bring it upto date for others. 

If you or @harraps want to take ownership of the p2/cannon definitions and would find it easier to maintain, or want to push them to Definitely Typed, you are more than welcome to.  I do not want any credit as they would have been useless without you guys effort of late. 

Thanks a lot :dancer:

**Comment by elisee** [comment]
Cool! @schteppe has [committed](https://github.com/schteppe/p2.js/blob/master/index.d.ts) the p2.js definition file into the official repository. Maybe he'll want to do the same for Cannon.js? :)

Cheers!

**Comment by schteppe** [comment]
Sure! Should be easy. Let me know how the p2 definition does and I'll do the exact same thing for cannon. @elisee

**Comment by elisee** [comment]
@schteppe So, I recently found out it won't work as is. After much headscratching, it turns out the `index.d.ts` file must be an "ambient module declaration" (_not_ an "ambient external module declaration", nor an "internal module"), like here: https://github.com/sparklinlabs/dnd-tree-view/blob/master/index.d.ts

So basically, we need to loose the `declare module p2 {` and also **maybe** replace the `export`s by `declare`s in front of each class (not sure about this part). I'll try and send a pull request soon!

**Comment by clark-stevenson** [comment]
Not sure if this is the same issue but in `p2` for example:

`declare module p2 {`  on the first line of the definition is not good enough for external modules. 

Last in the definition file is this:

```
declare module 'p2' {
    export = p2;
}
```

It works with SystemJS and that is how `p2` and `pixi` definitions are defined.  However, it is really pure guess work. Finding an exact answer is pretty tough.

**Comment by schteppe** [comment]
All right, let me know if I should change anything for p2. I don't really know how to do this correctly. Maybe the `tsconfig.json` should be included, specifying commonjs etc?

**Pull request merged**
