### PR TITLE
added boundingRadius property to Body type

### PR DESCRIPTION
**Pull request by ali-jawad**

### CODE REVIEW

**Comment by clark-stevenson** [comment]
👍 thanks!

**Comment by ali-jawad** [comment]
Thanks to you for this typing! :) I'm making good use of it.

**Comment by clark-stevenson** [comment]
Good to see someone getting use from it! I never got to use it in the end, it may be fairly outdated though as you may have noticed.

**Comment by ali-jawad** [comment]
Don't worry, CannonJS itself didn't change since mid of 2016 haha.

**Pull request merged**
